baseURL = "https://shenting.org/"
languageCode = "en-us"
title = "Shen Ting Ang"
theme = "PaperMod"

[params]
  author = "Shen Ting"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  homeInfoParams = { Title = "Welcome!", Content = "Welcome to my website. I write about data science, bridge, and technology." }

[outputs]
  home = ["HTML", "RSS", "JSON"]