baseURL = "https://shenting.org/"
languageCode = "en-us"
title = "Shen Ting Ang"
theme = "PaperMod"

[params]
  author = "Shen Ting"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowEdit = false
  disableSpecial1stPost = true
  disableScrollToTop = true

  # Homepage intro (PaperMod style)
  homeInfoParams = { 
    Title = "Welcome!", 
    Content = "Welcome to my website. I write about data science, bridge, and technology." 
  }

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/post/"
  weight = 2

[[menu.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/angshenting/"
  weight = 3